---
- name: install nginx
  yum:
    name: nginx
    state: installed

- name: copy nginx.conf
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644

- name: start nginx
  service:
    name: nginx
    state: started
